### ISSUE TITLE
Questions and ideas [Schema defined DB + Delegating capacity]

### ISSUE THREAD

**Issue by esteem8** [EOSIO/Documentation#1]
#### Schema Defined DB

 * What about using [BSON](http://bsonspec.org/) to permit Date type and a BinData type data types storage ?
 * Will there be indexes on the DB (for tables row and arrays in JSON)?
 * Will the DB be able to do an action (B.E. notify change) without the need of querying (based on DB inputs not DB queries)?

#### Delegating Capacity

 * Is it possible to define a logic based on parameters to automatically delegate capacity?

**Comment by HackG** [comment]
I don't think your going to get any good answers here... pretty sure this is another ICO scam.  They say straight up these tokens will have no use, no purpose, and can't be used on the EOS platform, IF someday the platform is even launched.

Take note from the terms for token sale:

“EOS TOKENS HAVE NO RIGHTS, USES OR ATTRIBUTES. The EOS Tokens do not have any rights, uses, purpose, attributes, functionalities or features, express or implied, including, without limitation, any uses, purpose, attributes, functionalities or features on the EOS Platform. The company does not guarantee and is not representing in any way to Buyer that the EOS Tokens have any rights, uses, purpose, attributes, functionalities or features. Company will have no control over when, how or whether the EOS.IO Software is adopted or implemented, or how, when or whether the EOS Platform is launched.”

“NOT A PURCHASE OF EOS PLATFORM TOKENS. EOS Tokens purchased under this Agreement are not tokens on the EOS Platform. Buyer acknowledges, understands and agrees that Buyer should not expect and there is no guarantee or representation made by Company that Buyer will receive any other product, service, rights, attributes, functionalities, features or assets of any kind whatsoever, including, without limitation, any cryptographic tokens or digital assets now or in the future whether through receipt,”

**Comment by cryptonut** [comment]
If you actually read whe white paper, and listen to the EOS guys speak, you'll see the ERC20 tokens you purchase are the right to vote to start the EOS block chain. 

If you register your token, you're voting via a smart contract to begin the eos network.

As long as 2 people vote, there will be an eos network.

I know of a few already (myself included) so... we will have an eos network.

One ERC20 token = 1 vote (as far as I understand it) and each vote will be your "stake" in the new eos network.

Pretty simple really and the whole ICO design is fricken genius if you ask me. Real anarcho capitalism at work.

If anyone from eos @bytemaster or anyone else can confirm my comments I'd be super grateful :-) @dbrock

**Comment by HackG** [comment]
So people paid for EOS tokens just to vote to start the network? 

Do the EOS Tokens have any rights, uses, purpose, attributes, functionalities or features, express or implied, including, without limitation, any uses, purpose, attributes, functionalities or features on the EOS Platform? The ICO terms say no

Do they represent any value or assets? The ICO terms say no

You say they allow a vote to start the network... so all those tokens sold and just 2 could have done the job lol

**Comment by cryptonut** [comment]
They can not guarantee there will even be an eos block chain as they are leaving that in the hands of smart investors to recognise the value, and register their tokens to start the chain. 

If they tried to patent / own and chain, they put it at risk of being taken over or of it being compromised, they want to build DAPPS on a network like eos, they know they have to build it to be able to build the DAPPS / businesses on it and they know that by making it a public chain they get the distribution and security they need for their businesses to work. They're not doing it as a pure charity but they clearly recognise what they're building will be more valuable to the community, and more valuable to them if they build it, set it free and then get down to the busieness of building DAPPS and businesses on it.

Block.one will no doubt be feverishly building apps for eos from sept launch of the test net until launch, these guys are going to be billionaires from creating businesses on eos, I'm going to be a millionaire from owning a few thousand eos tokens. You're going to remain where ever the hell you are in life because you're too stupid or too jaded to see what's right in front of your eyes.

Come back and check in with me in Dec 2018 and we'll compare notes then...

I'd usually have been a tad more gentle with my comments however it's pretty clear you have no desire to learn / understand, you're just here to troll.

Well now whoever comes along to read your little troll post can read something to counter it...

**Comment by cryptonut** [comment]
and surely someone who works for a medical market research company is intelligent enough to work this out for yourself ;-)

**Comment by bytemaster** [comment]
With respect to the original question, the database rows will be stored as binary and converted to/from JSON based on an ABI specification. It will be possible to get notifications on changes to individual rows of the DB.

With respect to the off-topic disucssion, yes block.one is creating eos.io so that we have a platform on which to build killer apps which have thus far not been publicly disclosed.
